name: rilaby.me
# url: "http://www.rilaby.me"
url: http://localhost:4000
title: "Uladzimir Karabeinik"

author:
  name: Uladzimir Karabeinik
  email: uladzimir.karabeinik@gmail.com

title: Your awesome title
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""

twitter_username: rilaby
github_username:  rilaby

permalink: :year/:month/:day/:title.html
copyright: "(c) Uladzimir Karabeinik, 2016"
encoding: utf-8
timezone: Europe/Minsk

markdown: kramdown

sass:
  sass_dir: _sass
  style: compresed
